apiVersion: v1
kind: Pod
metadata:
  name: s1-pending-pod
spec:
  containers:
  - name: nginx
    image: nginx
  nodeSelector:
    node: node1
    
    # resources:
    #   limits:
    #     cpu: 200m
    #     memory: 128Mi
    #   requests:
    #     cpu: 200m
    #     memory: 128Mi
    