apiVersion: v1
kind: Pod
metadata:
  name: s2-waiting-pod
spec:
  initContainers:
  - name: init-container
    image: nginx
    command: ["/bin/sh", "-c"]
    args:
    - |
      echo "Sleeping for 60 seconds in init container..."
      sleep 60
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
