apiVersion: v1
kind: Pod
metadata:
  name: s7-curlnotexistclusterip-pod
spec:
  containers:
  - name: curl
    image: curlimages/curl:latest
    command: ["/bin/sh", "-c"]
    args:
    - |
      echo "Trying to access non-existing ClusterIP service..."
      curl http://non-existing-service.default.svc.cluster.local
  restartPolicy: Never